# fly.toml app configuration file generated for babes-bookstore-ziaarq on 2026-09-27T16:06:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'babes-bookstore-ziaarq'
primary_region = 'lhr'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  APP_NAME = 'Babe\u0027s Bookstore'
  CELERY_CONCURRENCY = '4'
  DEBUG = 'false'
  FRONTEND_URL = 'https://babesbooks.store'
  PORT = '8000'
  WEB_CONCURRENCY = '2'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '20s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
  processes = ['worker']
